//! Events emitted by the game engine

use crate::state::{
    BuildItem, ColonyId, ColonyRole, CustomDesignId, DiplomaticCommunicationType, EmpireId,
    FleetFormation, FleetId, FleetOrder, FleetRole, HullId, PlanetAnomaly, PlanetSpecial, StarId,
    StrategicResource, TechId, TreatyType, VictoryPath,
};
#[cfg(feature = "serde")]
use serde::{Deserialize, Serialize};

/// Events generated by the game engine in response to commands
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub enum Event {
    /// Turn has advanced
    TurnAdvanced { new_turn: u32 },
    /// Colony focus was set
    ColonyFocusSet { colony: ColonyId },
    /// Fleet has moved
    FleetMoved {
        fleet: FleetId,
        from: StarId,
        to: StarId,
    },
    /// Build item was queued
    BuildQueued { colony: ColonyId, item: BuildItem },
    /// Build item was cancelled
    BuildCancelled { colony: ColonyId },
    /// Build item completed
    BuildCompleted { colony: ColonyId, item: BuildItem },
    /// Colony produced resources
    ColonyProduced {
        colony: ColonyId,
        /// Credits generated this turn
        credits: i64,
        /// Science generated this turn
        research: i64,
        /// Food produced this turn
        food: i64,
        /// Effective industrial output this turn
        industry: i64,
        /// Credit maintenance cost at this colony this turn
        maintenance: i64,
    },
    /// Fleet was created
    FleetCreated { fleet: FleetId, location: StarId },
    /// A technology was selected for research
    ResearchSelected { tech: TechId },
    /// A technology was queued for future research
    ResearchQueued { tech: TechId },
    /// A technology was removed from the research queue
    ResearchQueueRemoved { tech: TechId },
    /// The research queue order changed
    ResearchQueueReordered {
        tech: TechId,
        from_index: usize,
        to_index: usize,
    },
    /// All queued research entries were removed
    ResearchQueueCleared { removed_count: usize },
    /// Research points were generated empire-wide this turn
    ScienceGenerated { empire: EmpireId, amount: i64 },
    /// Research progress was made toward the active technology
    ResearchProgress {
        tech: TechId,
        gained: i64,
        total: i64,
        cost: i64,
    },
    /// A technology research was completed
    ResearchCompleted { tech: TechId },
    /// Active research automatically switched to a queued technology
    QueuedResearchStarted { tech: TechId },
    /// A queued technology was skipped during automatic queue processing
    QueuedResearchSkipped { tech: TechId, reason: String },
    /// Queue transition summary emitted after a research completion
    ResearchCompletedWithQueueTransition {
        completed: TechId,
        started: Option<TechId>,
    },
    /// Hyperspace Cartography was completed, enabling lane travel for known lanes
    HyperspaceCartographyUnlocked { empire: EmpireId },
    /// A scout fleet has been dispatched toward an unexplored system
    ScoutDispatched {
        fleet: FleetId,
        destination: StarId,
        turns_remaining: u32,
    },
    /// A science fleet has started surveying a planet
    SurveyStarted {
        fleet: FleetId,
        star: StarId,
        planet_index: usize,
        turns_remaining: u32,
    },
    /// A star system has been explored by a scout
    SystemExplored { star: StarId },
    /// Survey intel for a planet has been completed
    PlanetSurveyCompleted { star: StarId, planet_index: usize },
    /// Ancient Ruins were discovered during a planetary survey (one-time per planet).
    AncientRuinsDiscovered { star: StarId, planet_index: usize },
    /// A significant planet special was identified during survey.
    PlanetSpecialDiscovered {
        star: StarId,
        planet_index: usize,
        special: PlanetSpecial,
    },
    /// An anomaly was detected during survey and analysis.
    AnomalyDetected {
        star: StarId,
        planet_index: usize,
        anomaly: PlanetAnomaly,
    },
    /// Strategic resource was identified during survey (if discovery prerequisites are met).
    StrategicResourceDiscovered {
        star: StarId,
        planet_index: usize,
        resource: StrategicResource,
    },
    /// A fleet has departed toward an explored system (multi-turn movement)
    FleetDeparted {
        fleet: FleetId,
        from: StarId,
        to: StarId,
        turns_remaining: u32,
    },
    /// A fleet has arrived at its destination
    FleetArrived { fleet: FleetId, star: StarId },
    /// A fleet used a direct hyperspace lane for transit
    HyperspaceLaneUsed {
        empire: EmpireId,
        fleet: FleetId,
        from: StarId,
        to: StarId,
    },
    /// A colonization attempt has started for a specific target planet
    ColonizationStarted {
        empire: EmpireId,
        fleet: FleetId,
        star: StarId,
        planet_index: usize,
    },
    /// A colonizer fleet has successfully founded a new colony
    ColonizationCompleted {
        empire: EmpireId,
        fleet: FleetId,
        star: StarId,
        planet_index: usize,
        colony: ColonyId,
    },
    /// Strategic invasion captured a colony
    InvasionSucceeded {
        attacker: EmpireId,
        defender: EmpireId,
        fleet: FleetId,
        star: StarId,
        planet_index: usize,
        colony: ColonyId,
        transports_lost: u32,
    },
    /// Strategic invasion failed
    InvasionFailed {
        attacker: EmpireId,
        defender: EmpireId,
        fleet: FleetId,
        star: StarId,
        planet_index: usize,
        colony: ColonyId,
        invasion_strength: u32,
        defense_strength: u32,
        transports_lost: u32,
        reason: String,
    },
    /// Per-empire economy summary for this turn
    EconomySummary {
        empire: EmpireId,
        /// Credits income generated by colonies this turn (before maintenance)
        credits_income: i64,
        /// Credit maintenance cost from fleets and buildings this turn
        maintenance: i64,
        /// Total food produced by colonies this turn
        food_produced: i64,
        /// Total food consumed by population this turn
        food_consumed: i64,
    },
    /// Colony-level pressure report emitted when shortages or unemployment occur.
    ColonyStatusWarning {
        colony: ColonyId,
        food_deficit: i64,
        housing_deficit: u64,
        unemployed: u64,
    },
    /// A colony population increase occurred this turn.
    PopulationGrew {
        colony: ColonyId,
        new_population: u64,
    },
    /// Empire food supply is negative — population is underfed
    FoodShortage {
        empire: EmpireId,
        /// How far below zero the food stockpile fell (positive deficit amount)
        deficit: i64,
    },
    /// Empire credit balance is negative — maintenance exceeds income
    CreditDeficit {
        empire: EmpireId,
        /// How far below zero the credit balance fell (positive deficit amount)
        deficit: i64,
    },
    /// A colony lost trade-network connectivity and is now isolated
    ColonyIsolated { colony: ColonyId },
    /// A previously isolated colony regained trade-network connectivity
    ColonyReconnected { colony: ColonyId },
    /// An error occurred
    Error { message: String },
    /// AI empire has selected a technology to research
    AiResearchSelected { empire: EmpireId, tech: TechId },
    /// AI empire has queued a build item at a colony
    AiBuildQueued {
        empire: EmpireId,
        colony: ColonyId,
        item: BuildItem,
    },
    /// AI empire has dispatched a scout fleet toward an unexplored system
    AiScoutDispatched {
        empire: EmpireId,
        fleet: FleetId,
        destination: StarId,
    },
    /// AI empire has dispatched a combat fleet toward an enemy colony
    AiCombatFleetDispatched {
        empire: EmpireId,
        fleet: FleetId,
        destination: StarId,
    },
    /// AI empire has founded a new colony
    AiColonized {
        empire: EmpireId,
        star: StarId,
        planet_index: usize,
        colony: ColonyId,
    },
    /// First diplomatic contact has been established with another empire
    FirstContact {
        /// The empire that the player has made first contact with
        with_empire: EmpireId,
    },
    /// A diplomatic communication has been generated.
    DiplomaticCommunicationCreated {
        communication_id: u64,
        from_empire: EmpireId,
        to_empire: EmpireId,
        communication_type: DiplomaticCommunicationType,
    },
    /// A treaty was formally proposed.
    TreatyProposed {
        from_empire: EmpireId,
        to_empire: EmpireId,
        treaty_type: TreatyType,
    },
    /// A treaty proposal was accepted.
    TreatyAccepted {
        from_empire: EmpireId,
        to_empire: EmpireId,
        treaty_type: TreatyType,
    },
    /// A treaty proposal was rejected.
    TreatyRejected {
        from_empire: EmpireId,
        to_empire: EmpireId,
        treaty_type: TreatyType,
    },
    /// A treaty became active.
    TreatySigned {
        with_empire: EmpireId,
        treaty_type: TreatyType,
        expires_turn: u32,
    },
    /// An active treaty expired.
    TreatyExpired {
        with_empire: EmpireId,
        treaty_type: TreatyType,
    },
    /// An active treaty was cancelled.
    TreatyCancelled {
        with_empire: EmpireId,
        treaty_type: TreatyType,
    },
    /// A diplomatic warning was issued.
    WarningIssued {
        from_empire: EmpireId,
        to_empire: EmpireId,
    },
    /// A tribute demand was issued.
    TributeDemanded {
        from_empire: EmpireId,
        to_empire: EmpireId,
    },
    /// A tribute demand was refused.
    TributeRefused {
        from_empire: EmpireId,
        to_empire: EmpireId,
    },
    /// War was declared by one empire on another.
    WarDeclared {
        attacker: EmpireId,
        defender: EmpireId,
    },
    /// Peace was signed and war ended.
    PeaceSigned {
        with_empire: EmpireId,
        truce_expires_turn: u32,
    },
    /// Relationship status changed between player and a foreign empire.
    RelationshipStateChanged {
        with_empire: EmpireId,
        from: crate::state::RelationshipStatus,
        to: crate::state::RelationshipStatus,
    },
    /// Combat was auto-resolved between two hostile fleets at a star system
    CombatResolved {
        /// The star system where combat occurred
        star: StarId,
        /// The first fleet involved in combat
        fleet_a: FleetId,
        /// Owner empire of fleet_a
        empire_a: EmpireId,
        /// The second fleet involved in combat
        fleet_b: FleetId,
        /// Owner empire of fleet_b
        empire_b: EmpireId,
        /// Combat strength of fleet_a
        strength_a: u32,
        /// Combat strength of fleet_b
        strength_b: u32,
        /// Integrity remaining for fleet_a after combat (0 = destroyed)
        integrity_a_remaining: u32,
        /// Integrity remaining for fleet_b after combat (0 = destroyed)
        integrity_b_remaining: u32,
        /// Whether fleet_a was destroyed
        fleet_a_destroyed: bool,
        /// Whether fleet_b was destroyed
        fleet_b_destroyed: bool,
    },
    /// A colony's specialisation role was changed by the player
    ColonyRoleChanged { colony: ColonyId, role: ColonyRole },
    /// AI empire assigned a specialisation role to one of its colonies
    AiColonyRoleAssigned {
        empire: EmpireId,
        colony: ColonyId,
        role: ColonyRole,
    },
    /// A rally point was set for a colony
    RallyPointSet { colony: ColonyId, star: StarId },
    /// The rally point for a colony was cleared
    RallyPointCleared { colony: ColonyId },
    /// A standing fleet order was set
    FleetOrderSet { fleet: FleetId, order: FleetOrder },
    /// A fleet's strategic role was changed.
    FleetRoleChanged { fleet: FleetId, role: FleetRole },
    /// A fleet's formation posture was changed.
    FleetFormationChanged {
        fleet: FleetId,
        formation: FleetFormation,
    },
    /// A fleet was renamed.
    FleetRenamed { fleet: FleetId, name: String },
    /// A newly produced ship was automatically routed toward the colony's rally point
    ShipRoutedToRallyPoint {
        fleet: FleetId,
        colony: ColonyId,
        from: StarId,
        to: StarId,
        turns_remaining: u32,
    },
    /// A colony has come under blockade by a hostile empire
    BlockadeStarted {
        /// The blockaded colony
        colony: ColonyId,
        /// The star system where the blockade is taking effect
        star: StarId,
        /// The empire imposing the blockade
        by_empire: EmpireId,
    },
    /// A specific fleet established a blockade over an enemy colony.
    BlockadeFleetEstablished {
        fleet: FleetId,
        colony: ColonyId,
        star: StarId,
        by_empire: EmpireId,
    },
    /// A colony's blockade has been lifted
    BlockadeEnded {
        /// The colony that was blockaded
        colony: ColonyId,
        /// The star system where the blockade ended
        star: StarId,
    },
    /// A major victory-path progress milestone was reached.
    VictoryProgressMilestone {
        path: VictoryPath,
        empire: EmpireId,
        progress_percent: u8,
    },
    /// A winner has been determined by configured victory conditions.
    VictoryAchieved {
        winner: EmpireId,
        path: VictoryPath,
        turn: u32,
    },
    /// A player or AI empire created a custom ship design.
    ShipDesignCreated {
        empire: EmpireId,
        design_id: CustomDesignId,
        hull_id: HullId,
        name: String,
    },
    /// A custom ship design was marked obsolete and removed.
    ShipDesignDeleted {
        empire: EmpireId,
        design_id: CustomDesignId,
    },
    /// Validation of a custom ship design failed.
    ShipDesignInvalid {
        empire: EmpireId,
        hull_id: HullId,
        reason: String,
    },
    /// A ship built from a custom design was completed at a colony.
    CustomShipConstructed {
        empire: EmpireId,
        colony: ColonyId,
        design_id: CustomDesignId,
        fleet: FleetId,
    },
    /// A fleet intentfully assembled as an invasion task force.
    InvasionFleetAssembled {
        empire: EmpireId,
        fleet: FleetId,
        star: StarId,
    },
    /// Combat engagement has started between two fleets.
    FleetEngagementStarted {
        star: StarId,
        fleet_a: FleetId,
        fleet_b: FleetId,
    },
    /// A fleet disengaged from combat and is retreating.
    FleetRetreatTriggered {
        fleet: FleetId,
        from_star: StarId,
        to_star: StarId,
        remaining_integrity: u32,
    },
}

impl Event {
    /// Create an error event
    pub fn error(message: impl Into<String>) -> Self {
        Event::Error {
            message: message.into(),
        }
    }

    /// Convert event to a log message
    pub fn to_log_message(&self) -> String {
        match self {
            Event::TurnAdvanced { new_turn } => format!("Turn {} begins", new_turn),
            Event::ColonyFocusSet { colony } => format!("Colony {} focus updated", colony.0),
            Event::FleetMoved { fleet, from, to } => {
                format!("Fleet {} moved from {} to {}", fleet.0, from.0, to.0)
            }
            Event::BuildQueued { colony, item } => {
                format!(
                    "Colony {} queued {} ({})",
                    colony.0,
                    item.name(),
                    item.category_name()
                )
            }
            Event::BuildCancelled { colony } => {
                format!("Colony {} cancelled build", colony.0)
            }
            Event::BuildCompleted { colony, item } => {
                format!(
                    "Colony {} completed {} ({})",
                    colony.0,
                    item.name(),
                    item.category_name()
                )
            }
            Event::ColonyProduced {
                colony,
                credits,
                research,
                food,
                // industry and maintenance are available for UI/summary display
                // but omitted from the log message to keep it concise.
                industry: _,
                maintenance: _,
            } => {
                format!(
                    "Colony {} produced {} credits, {} research, {} food",
                    colony.0, credits, research, food
                )
            }
            Event::FleetCreated { fleet, location } => {
                format!("Fleet {} created at star {}", fleet.0, location.0)
            }
            Event::ResearchSelected { tech } => {
                format!("Research started: tech {}", tech.0)
            }
            Event::ResearchQueued { tech } => {
                format!("Research queued: tech {}", tech.0)
            }
            Event::ResearchQueueRemoved { tech } => {
                format!("Research queue removed: tech {}", tech.0)
            }
            Event::ResearchQueueReordered {
                tech,
                from_index,
                to_index,
            } => {
                format!(
                    "Research queue reordered: tech {} moved {}→{}",
                    tech.0, from_index, to_index
                )
            }
            Event::ResearchQueueCleared { removed_count } => {
                format!("Research queue cleared: {} removed", removed_count)
            }
            Event::ScienceGenerated { empire, amount } => {
                format!("Empire {} generated {} science this turn", empire.0, amount)
            }
            Event::ResearchProgress {
                tech,
                gained,
                total,
                cost,
            } => {
                format!(
                    "Research: +{} rp on tech {} ({}/{} rp)",
                    gained, tech.0, total, cost
                )
            }
            Event::ResearchCompleted { tech } => {
                format!("Research complete: tech {}", tech.0)
            }
            Event::QueuedResearchStarted { tech } => {
                format!("Queued research started: tech {}", tech.0)
            }
            Event::QueuedResearchSkipped { tech, reason } => {
                format!("Queued research skipped: tech {} ({})", tech.0, reason)
            }
            Event::ResearchCompletedWithQueueTransition { completed, started } => match started {
                Some(tech) => format!(
                    "Research transition: tech {} complete, queued tech {} started",
                    completed.0, tech.0
                ),
                None => format!(
                    "Research transition: tech {} complete, no queued tech started",
                    completed.0
                ),
            },
            Event::HyperspaceCartographyUnlocked { empire } => {
                format!(
                    "Empire {} unlocked Hyperspace Cartography — known lanes are now usable",
                    empire.0
                )
            }
            Event::ScoutDispatched {
                fleet,
                destination,
                turns_remaining,
            } => {
                format!(
                    "Scout {} dispatched to system {} ({} turns)",
                    fleet.0, destination.0, turns_remaining
                )
            }
            Event::SurveyStarted {
                fleet,
                star,
                planet_index,
                turns_remaining,
            } => {
                format!(
                    "Science ship {} started survey at system {} orbit {} ({} turns)",
                    fleet.0,
                    star.0,
                    planet_index + 1,
                    turns_remaining
                )
            }
            Event::SystemExplored { star } => {
                format!("System {} explored", star.0)
            }
            Event::PlanetSurveyCompleted { star, planet_index } => {
                format!(
                    "Survey completed: system {} orbit {}",
                    star.0,
                    planet_index + 1
                )
            }
            Event::AncientRuinsDiscovered { star, planet_index } => {
                format!(
                    "DISCOVERY: Ancient Ruins found at system {} orbit {} — +2 science per turn",
                    star.0,
                    planet_index + 1
                )
            }
            Event::PlanetSpecialDiscovered {
                star,
                planet_index,
                special,
            } => {
                format!(
                    "DISCOVERY: {} identified at system {} orbit {} — {}",
                    special.name(),
                    star.0,
                    planet_index + 1,
                    special.description()
                )
            }
            Event::AnomalyDetected {
                star,
                planet_index,
                anomaly,
            } => {
                let risk = anomaly
                    .risk_level()
                    .map(|level| format!(" [{} risk]", level.label()))
                    .unwrap_or_default();
                format!(
                    "ANOMALY: {} detected at system {} orbit {}{} — {}",
                    anomaly.name(),
                    star.0,
                    planet_index + 1,
                    risk,
                    anomaly.description()
                )
            }
            Event::StrategicResourceDiscovered {
                star,
                planet_index,
                resource,
            } => {
                format!(
                    "DISCOVERY: {} identified at system {} orbit {}",
                    resource.name(),
                    star.0,
                    planet_index + 1
                )
            }
            Event::FleetDeparted {
                fleet,
                from,
                to,
                turns_remaining,
            } => {
                format!(
                    "Fleet {} departed from {} toward {} ({} turns)",
                    fleet.0, from.0, to.0, turns_remaining
                )
            }
            Event::FleetArrived { fleet, star } => {
                format!("Fleet {} arrived at system {}", fleet.0, star.0)
            }
            Event::HyperspaceLaneUsed {
                empire,
                fleet,
                from,
                to,
            } => {
                format!(
                    "Empire {}: Fleet {} used hyperspace lane {} ↔ {}",
                    empire.0, fleet.0, from.0, to.0
                )
            }
            Event::ColonizationStarted {
                empire,
                fleet,
                star,
                planet_index,
            } => {
                format!(
                    "Empire {} started colonization with fleet {} at system {} orbit {}",
                    empire.0,
                    fleet.0,
                    star.0,
                    planet_index + 1
                )
            }
            Event::ColonizationCompleted {
                empire,
                fleet: _,
                star,
                planet_index,
                colony,
            } => {
                format!(
                    "Empire {} founded colony {} at system {} orbit {}",
                    empire.0,
                    colony.0,
                    star.0,
                    planet_index + 1
                )
            }
            Event::InvasionSucceeded {
                attacker,
                defender,
                fleet,
                star,
                planet_index,
                colony,
                transports_lost,
            } => {
                format!(
                    "INVASION SUCCESS: Empire {} captured colony {} from Empire {} at system {} orbit {} using transport {} (lost {})",
                    attacker.0,
                    colony.0,
                    defender.0,
                    star.0,
                    planet_index + 1,
                    fleet.0,
                    transports_lost
                )
            }
            Event::InvasionFailed {
                attacker,
                defender,
                fleet,
                star,
                planet_index,
                colony,
                invasion_strength,
                defense_strength,
                transports_lost,
                reason,
            } => {
                format!(
                    "INVASION FAILED: Empire {} vs Empire {} at colony {} (system {} orbit {}) using transport {} — {} (strength {} vs {}, lost {})",
                    attacker.0,
                    defender.0,
                    colony.0,
                    star.0,
                    planet_index + 1,
                    fleet.0,
                    reason,
                    invasion_strength,
                    defense_strength,
                    transports_lost
                )
            }
            Event::EconomySummary {
                empire,
                credits_income,
                maintenance,
                food_produced,
                food_consumed,
            } => {
                format!(
                    "Empire {} economy: +{} credits income, -{} maintenance, +{} food, -{} consumed",
                    empire.0, credits_income, maintenance, food_produced, food_consumed
                )
            }
            Event::ColonyStatusWarning {
                colony,
                food_deficit,
                housing_deficit,
                unemployed,
            } => format!(
                "WARNING: Colony {} pressure — food deficit {}, housing deficit {}, unemployed {}",
                colony.0, food_deficit, housing_deficit, unemployed
            ),
            Event::PopulationGrew {
                colony,
                new_population,
            } => format!("Colony {} population grew to {}", colony.0, new_population),
            Event::FoodShortage { empire, deficit } => {
                format!(
                    "WARNING: Empire {} food shortage — deficit {}",
                    empire.0, deficit
                )
            }
            Event::CreditDeficit { empire, deficit } => {
                format!(
                    "WARNING: Empire {} credit deficit — deficit {}",
                    empire.0, deficit
                )
            }
            Event::ColonyIsolated { colony } => {
                format!(
                    "WARNING: Colony {} is now isolated from trade network",
                    colony.0
                )
            }
            Event::ColonyReconnected { colony } => {
                format!("Colony {} reconnected to trade network", colony.0)
            }
            Event::Error { message } => format!("Error: {}", message),
            Event::AiResearchSelected { empire, tech } => {
                format!("AI Empire {}: researching tech {}", empire.0, tech.0)
            }
            Event::AiBuildQueued {
                empire,
                colony,
                item,
            } => {
                format!(
                    "AI Empire {}: queued {} at colony {}",
                    empire.0,
                    item.name(),
                    colony.0
                )
            }
            Event::AiScoutDispatched {
                empire,
                fleet,
                destination,
            } => {
                format!(
                    "AI Empire {}: scout {} dispatched to system {}",
                    empire.0, fleet.0, destination.0
                )
            }
            Event::AiCombatFleetDispatched {
                empire,
                fleet,
                destination,
            } => {
                format!(
                    "AI Empire {}: combat fleet {} dispatched toward system {}",
                    empire.0, fleet.0, destination.0
                )
            }
            Event::AiColonized {
                empire,
                star,
                planet_index,
                colony,
            } => {
                format!(
                    "AI Empire {}: colonized system {} planet {} (colony {})",
                    empire.0, star.0, planet_index, colony.0
                )
            }
            Event::FirstContact { with_empire } => {
                format!(
                    "FIRST CONTACT: Diplomatic contact established with Empire {}",
                    with_empire.0
                )
            }
            Event::DiplomaticCommunicationCreated {
                communication_id,
                from_empire,
                to_empire,
                communication_type,
            } => format!(
                "Diplomatic communication {}: {:?} from Empire {} to Empire {}",
                communication_id, communication_type, from_empire.0, to_empire.0
            ),
            Event::TreatyProposed {
                from_empire,
                to_empire,
                treaty_type,
            } => format!(
                "Empire {} proposed {} to Empire {}",
                from_empire.0,
                treaty_type.label(),
                to_empire.0
            ),
            Event::TreatyAccepted {
                from_empire,
                to_empire,
                treaty_type,
            } => format!(
                "Empire {} accepted {} with Empire {}",
                to_empire.0,
                treaty_type.label(),
                from_empire.0
            ),
            Event::TreatyRejected {
                from_empire,
                to_empire,
                treaty_type,
            } => format!(
                "Empire {} rejected {} from Empire {}",
                to_empire.0,
                treaty_type.label(),
                from_empire.0
            ),
            Event::TreatySigned {
                with_empire,
                treaty_type,
                expires_turn,
            } => format!(
                "{} signed with Empire {} (expires turn {})",
                treaty_type.label(),
                with_empire.0,
                expires_turn
            ),
            Event::TreatyExpired {
                with_empire,
                treaty_type,
            } => format!(
                "{} with Empire {} expired",
                treaty_type.label(),
                with_empire.0
            ),
            Event::TreatyCancelled {
                with_empire,
                treaty_type,
            } => format!(
                "{} with Empire {} cancelled",
                treaty_type.label(),
                with_empire.0
            ),
            Event::WarningIssued {
                from_empire,
                to_empire,
            } => format!(
                "Empire {} issued warning to Empire {}",
                from_empire.0, to_empire.0
            ),
            Event::TributeDemanded {
                from_empire,
                to_empire,
            } => format!(
                "Empire {} demanded tribute from Empire {}",
                from_empire.0, to_empire.0
            ),
            Event::TributeRefused {
                from_empire,
                to_empire,
            } => format!(
                "Empire {} refused tribute demand from Empire {}",
                to_empire.0, from_empire.0
            ),
            Event::WarDeclared { attacker, defender } => {
                format!(
                    "WAR DECLARED: Empire {} declared war on Empire {}",
                    attacker.0, defender.0
                )
            }
            Event::PeaceSigned {
                with_empire,
                truce_expires_turn,
            } => format!(
                "Peace signed with Empire {} (truce until turn {})",
                with_empire.0, truce_expires_turn
            ),
            Event::RelationshipStateChanged {
                with_empire,
                from,
                to,
            } => format!(
                "Diplomatic status with Empire {} changed: {} → {}",
                with_empire.0,
                from.label(),
                to.label()
            ),
            Event::CombatResolved {
                star,
                fleet_a,
                empire_a,
                fleet_b,
                empire_b,
                strength_a,
                strength_b,
                integrity_a_remaining,
                integrity_b_remaining,
                fleet_a_destroyed,
                fleet_b_destroyed,
            } => {
                let result = match (fleet_a_destroyed, fleet_b_destroyed) {
                    (true, true) => "both fleets destroyed".to_string(),
                    (true, false) => format!(
                        "Fleet {} (Empire {}) destroyed; Fleet {} (Empire {}) survives at {}% integrity",
                        fleet_a.0, empire_a.0, fleet_b.0, empire_b.0, integrity_b_remaining
                    ),
                    (false, true) => format!(
                        "Fleet {} (Empire {}) survives at {}% integrity; Fleet {} (Empire {}) destroyed",
                        fleet_a.0, empire_a.0, integrity_a_remaining, fleet_b.0, empire_b.0
                    ),
                    (false, false) => format!(
                        "Fleet {} (Empire {}) at {}% integrity; Fleet {} (Empire {}) at {}% integrity",
                        fleet_a.0, empire_a.0, integrity_a_remaining,
                        fleet_b.0, empire_b.0, integrity_b_remaining
                    ),
                };
                format!(
                    "COMBAT at system {}: Fleet {} (Str:{}) vs Fleet {} (Str:{}) — {}",
                    star.0, fleet_a.0, strength_a, fleet_b.0, strength_b, result
                )
            }
            Event::ColonyRoleChanged { colony, role } => {
                format!("Colony {}: role set to {}", colony.0, role.name())
            }
            Event::AiColonyRoleAssigned {
                empire,
                colony,
                role,
            } => {
                format!(
                    "AI Empire {}: colony {} assigned role {}",
                    empire.0,
                    colony.0,
                    role.name()
                )
            }
            Event::RallyPointSet { colony, star } => {
                format!("Colony {}: rally point set to system {}", colony.0, star.0)
            }
            Event::RallyPointCleared { colony } => {
                format!("Colony {}: rally point cleared", colony.0)
            }
            Event::FleetOrderSet { fleet, order } => match order {
                FleetOrder::Hold => format!("Fleet {}: order set to Hold", fleet.0),
                FleetOrder::MoveToSystem(star) => {
                    format!("Fleet {}: order set — moving to system {}", fleet.0, star.0)
                }
            },
            Event::FleetRoleChanged { fleet, role } => {
                format!("Fleet {}: role set to {}", fleet.0, role.label())
            }
            Event::FleetFormationChanged { fleet, formation } => {
                format!("Fleet {}: formation set to {}", fleet.0, formation.label())
            }
            Event::FleetRenamed { fleet, name } => {
                format!("Fleet {} renamed to '{}'", fleet.0, name)
            }
            Event::ShipRoutedToRallyPoint {
                fleet,
                colony,
                from: _,
                to,
                turns_remaining,
            } => {
                format!(
                    "Fleet {} (from colony {}) routed to rally point system {} ({} turns)",
                    fleet.0, colony.0, to.0, turns_remaining
                )
            }
            Event::BlockadeStarted {
                colony,
                star,
                by_empire,
            } => {
                format!(
                    "WARNING: Colony {} at system {} is under blockade by Empire {}",
                    colony.0, star.0, by_empire.0
                )
            }
            Event::BlockadeFleetEstablished {
                fleet,
                colony,
                star,
                by_empire,
            } => format!(
                "Fleet {} (Empire {}) established blockade on colony {} at system {}",
                fleet.0, by_empire.0, colony.0, star.0
            ),
            Event::BlockadeEnded { colony, star } => {
                format!("Colony {} at system {} blockade lifted", colony.0, star.0)
            }
            Event::VictoryProgressMilestone {
                path,
                empire,
                progress_percent,
            } => {
                format!(
                    "VICTORY MILESTONE: Empire {} reached {}% toward {} victory",
                    empire.0,
                    progress_percent,
                    path.label()
                )
            }
            Event::VictoryAchieved { winner, path, turn } => {
                format!(
                    "VICTORY ACHIEVED: Empire {} won via {} on turn {}",
                    winner.0,
                    path.label(),
                    turn
                )
            }
            Event::ShipDesignCreated {
                empire,
                design_id,
                hull_id,
                name,
            } => {
                format!(
                    "Empire {}: custom design {} '{}' created (hull {})",
                    empire.0, design_id.0, name, hull_id.0
                )
            }
            Event::ShipDesignDeleted { empire, design_id } => {
                format!("Empire {}: custom design {} deleted", empire.0, design_id.0)
            }
            Event::ShipDesignInvalid {
                empire,
                hull_id,
                reason,
            } => {
                format!(
                    "Empire {}: ship design invalid for hull {} — {}",
                    empire.0, hull_id.0, reason
                )
            }
            Event::CustomShipConstructed {
                empire,
                colony,
                design_id,
                fleet,
            } => {
                format!(
                    "Empire {}: custom ship (design {}) completed at colony {} as fleet {}",
                    empire.0, design_id.0, colony.0, fleet.0
                )
            }
            Event::InvasionFleetAssembled {
                empire,
                fleet,
                star,
            } => format!(
                "Empire {} assembled invasion fleet {} at system {}",
                empire.0, fleet.0, star.0
            ),
            Event::FleetEngagementStarted {
                star,
                fleet_a,
                fleet_b,
            } => format!(
                "Combat engagement started at system {} between fleets {} and {}",
                star.0, fleet_a.0, fleet_b.0
            ),
            Event::FleetRetreatTriggered {
                fleet,
                from_star,
                to_star,
                remaining_integrity,
            } => format!(
                "Fleet {} retreating from system {} to {} at {}% integrity",
                fleet.0, from_star.0, to_star.0, remaining_integrity
            ),
        }
    }

    /// Check if this is an error event
    pub fn is_error(&self) -> bool {
        matches!(self, Event::Error { .. })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[cfg(feature = "serde")]
    #[test]
    fn event_serialization() {
        let event = Event::TurnAdvanced { new_turn: 5 };
        let json = serde_json::to_string(&event).unwrap();
        let parsed: Event = serde_json::from_str(&json).unwrap();
        assert_eq!(event, parsed);
    }

    #[test]
    fn error_event() {
        let event = Event::error("Something went wrong");
        assert!(event.is_error());
        match event {
            Event::Error { message } => assert_eq!(message, "Something went wrong"),
            _ => panic!("Expected error event"),
        }
    }

    #[test]
    fn log_message_formatting() {
        let event = Event::TurnAdvanced { new_turn: 10 };
        assert_eq!(event.to_log_message(), "Turn 10 begins");

        let event = Event::Error {
            message: "Test error".to_string(),
        };
        assert_eq!(event.to_log_message(), "Error: Test error");

        // Verify numeric IDs are formatted without debug brackets
        let event = Event::ColonyFocusSet {
            colony: crate::state::ColonyId(7),
        };
        assert_eq!(event.to_log_message(), "Colony 7 focus updated");

        let event = Event::FleetMoved {
            fleet: crate::state::FleetId(1),
            from: crate::state::StarId(2),
            to: crate::state::StarId(3),
        };
        assert_eq!(event.to_log_message(), "Fleet 1 moved from 2 to 3");

        let event = Event::ResearchSelected {
            tech: crate::state::TechId(3),
        };
        assert_eq!(event.to_log_message(), "Research started: tech 3");

        let event = Event::ResearchQueued {
            tech: crate::state::TechId(4),
        };
        assert_eq!(event.to_log_message(), "Research queued: tech 4");

        let event = Event::ResearchQueueReordered {
            tech: crate::state::TechId(4),
            from_index: 2,
            to_index: 1,
        };
        assert_eq!(
            event.to_log_message(),
            "Research queue reordered: tech 4 moved 2→1"
        );

        let event = Event::ScienceGenerated {
            empire: crate::state::EmpireId(1),
            amount: 42,
        };
        assert_eq!(
            event.to_log_message(),
            "Empire 1 generated 42 science this turn"
        );

        let event = Event::ResearchProgress {
            tech: crate::state::TechId(2),
            gained: 10,
            total: 30,
            cost: 80,
        };
        assert_eq!(
            event.to_log_message(),
            "Research: +10 rp on tech 2 (30/80 rp)"
        );

        let event = Event::ResearchCompleted {
            tech: crate::state::TechId(1),
        };
        assert_eq!(event.to_log_message(), "Research complete: tech 1");

        let event = Event::ScoutDispatched {
            fleet: crate::state::FleetId(2),
            destination: crate::state::StarId(9),
            turns_remaining: 3,
        };
        assert_eq!(
            event.to_log_message(),
            "Scout 2 dispatched to system 9 (3 turns)"
        );

        let event = Event::SystemExplored {
            star: crate::state::StarId(9),
        };
        assert_eq!(event.to_log_message(), "System 9 explored");
    }

    #[test]
    fn scout_dispatched_is_not_error() {
        let event = Event::ScoutDispatched {
            fleet: crate::state::FleetId(1),
            destination: crate::state::StarId(5),
            turns_remaining: 3,
        };
        assert!(!event.is_error());
    }

    #[test]
    fn survey_started_is_not_error() {
        let event = Event::SurveyStarted {
            fleet: crate::state::FleetId(1),
            star: crate::state::StarId(5),
            planet_index: 0,
            turns_remaining: 2,
        };
        assert!(!event.is_error());
    }

    #[test]
    fn system_explored_is_not_error() {
        let event = Event::SystemExplored {
            star: crate::state::StarId(5),
        };
        assert!(!event.is_error());
    }

    #[cfg(feature = "serde")]
    #[test]
    fn scout_dispatched_serialization() {
        let event = Event::ScoutDispatched {
            fleet: crate::state::FleetId(1),
            destination: crate::state::StarId(5),
            turns_remaining: 3,
        };
        let json = serde_json::to_string(&event).unwrap();
        let parsed: Event = serde_json::from_str(&json).unwrap();
        assert_eq!(event, parsed);
    }

    #[cfg(feature = "serde")]
    #[test]
    fn survey_started_serialization() {
        let event = Event::SurveyStarted {
            fleet: crate::state::FleetId(1),
            star: crate::state::StarId(5),
            planet_index: 2,
            turns_remaining: 2,
        };
        let json = serde_json::to_string(&event).unwrap();
        let parsed: Event = serde_json::from_str(&json).unwrap();
        assert_eq!(event, parsed);
    }

    #[cfg(feature = "serde")]
    #[test]
    fn system_explored_serialization() {
        let event = Event::SystemExplored {
            star: crate::state::StarId(7),
        };
        let json = serde_json::to_string(&event).unwrap();
        let parsed: Event = serde_json::from_str(&json).unwrap();
        assert_eq!(event, parsed);
    }

    #[test]
    fn fleet_departed_log_message() {
        let event = Event::FleetDeparted {
            fleet: crate::state::FleetId(2),
            from: crate::state::StarId(3),
            to: crate::state::StarId(7),
            turns_remaining: 2,
        };
        assert_eq!(
            event.to_log_message(),
            "Fleet 2 departed from 3 toward 7 (2 turns)"
        );
        assert!(!event.is_error());
    }

    #[test]
    fn fleet_arrived_log_message() {
        let event = Event::FleetArrived {
            fleet: crate::state::FleetId(4),
            star: crate::state::StarId(9),
        };
        assert_eq!(event.to_log_message(), "Fleet 4 arrived at system 9");
        assert!(!event.is_error());
    }

    #[cfg(feature = "serde")]
    #[test]
    fn fleet_departed_serialization() {
        let event = Event::FleetDeparted {
            fleet: crate::state::FleetId(1),
            from: crate::state::StarId(2),
            to: crate::state::StarId(5),
            turns_remaining: 2,
        };
        let json = serde_json::to_string(&event).unwrap();
        let parsed: Event = serde_json::from_str(&json).unwrap();
        assert_eq!(event, parsed);
    }

    #[cfg(feature = "serde")]
    #[test]
    fn fleet_arrived_serialization() {
        let event = Event::FleetArrived {
            fleet: crate::state::FleetId(3),
            star: crate::state::StarId(8),
        };
        let json = serde_json::to_string(&event).unwrap();
        let parsed: Event = serde_json::from_str(&json).unwrap();
        assert_eq!(event, parsed);
    }

    #[test]
    fn economy_summary_log_message() {
        let event = Event::EconomySummary {
            empire: crate::state::EmpireId(1),
            credits_income: 10,
            maintenance: 2,
            food_produced: 8,
            food_consumed: 5,
        };
        assert_eq!(
            event.to_log_message(),
            "Empire 1 economy: +10 credits income, -2 maintenance, +8 food, -5 consumed"
        );
        assert!(!event.is_error());
    }

    #[test]
    fn food_shortage_log_message() {
        let event = Event::FoodShortage {
            empire: crate::state::EmpireId(1),
            deficit: 3,
        };
        assert_eq!(
            event.to_log_message(),
            "WARNING: Empire 1 food shortage — deficit 3"
        );
        assert!(!event.is_error());
    }

    #[test]
    fn credit_deficit_log_message() {
        let event = Event::CreditDeficit {
            empire: crate::state::EmpireId(1),
            deficit: 5,
        };
        assert_eq!(
            event.to_log_message(),
            "WARNING: Empire 1 credit deficit — deficit 5"
        );
        assert!(!event.is_error());
    }

    #[cfg(feature = "serde")]
    #[test]
    fn economy_summary_serialization() {
        let event = Event::EconomySummary {
            empire: crate::state::EmpireId(1),
            credits_income: 10,
            maintenance: 2,
            food_produced: 8,
            food_consumed: 5,
        };
        let json = serde_json::to_string(&event).unwrap();
        let parsed: Event = serde_json::from_str(&json).unwrap();
        assert_eq!(event, parsed);
    }

    #[cfg(feature = "serde")]
    #[test]
    fn food_shortage_serialization() {
        let event = Event::FoodShortage {
            empire: crate::state::EmpireId(2),
            deficit: 7,
        };
        let json = serde_json::to_string(&event).unwrap();
        let parsed: Event = serde_json::from_str(&json).unwrap();
        assert_eq!(event, parsed);
    }

    #[cfg(feature = "serde")]
    #[test]
    fn credit_deficit_serialization() {
        let event = Event::CreditDeficit {
            empire: crate::state::EmpireId(2),
            deficit: 4,
        };
        let json = serde_json::to_string(&event).unwrap();
        let parsed: Event = serde_json::from_str(&json).unwrap();
        assert_eq!(event, parsed);
    }

    #[test]
    fn combat_resolved_is_not_error() {
        let event = Event::CombatResolved {
            star: crate::state::StarId(1),
            fleet_a: crate::state::FleetId(1),
            empire_a: crate::state::EmpireId(1),
            fleet_b: crate::state::FleetId(2),
            empire_b: crate::state::EmpireId(2),
            strength_a: 10,
            strength_b: 10,
            integrity_a_remaining: 0,
            integrity_b_remaining: 0,
            fleet_a_destroyed: true,
            fleet_b_destroyed: true,
        };
        assert!(!event.is_error());
    }

    #[cfg(feature = "serde")]
    #[test]
    fn combat_resolved_serialization() {
        let event = Event::CombatResolved {
            star: crate::state::StarId(3),
            fleet_a: crate::state::FleetId(1),
            empire_a: crate::state::EmpireId(1),
            fleet_b: crate::state::FleetId(2),
            empire_b: crate::state::EmpireId(2),
            strength_a: 20,
            strength_b: 10,
            integrity_a_remaining: 50,
            integrity_b_remaining: 0,
            fleet_a_destroyed: false,
            fleet_b_destroyed: true,
        };
        let json = serde_json::to_string(&event).unwrap();
        let parsed: Event = serde_json::from_str(&json).unwrap();
        assert_eq!(event, parsed);
    }
}
