//! Events emitted by the game engine

use crate::state::{BuildItem, ColonyId, EmpireId, FleetId, StarId, TechId};
#[cfg(feature = "serde")]
use serde::{Deserialize, Serialize};

/// Events generated by the game engine in response to commands
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub enum Event {
    /// Turn has advanced
    TurnAdvanced { new_turn: u32 },
    /// Colony focus was set
    ColonyFocusSet { colony: ColonyId },
    /// Fleet has moved
    FleetMoved {
        fleet: FleetId,
        from: StarId,
        to: StarId,
    },
    /// Build item was queued
    BuildQueued { colony: ColonyId, item: BuildItem },
    /// Build item was cancelled
    BuildCancelled { colony: ColonyId },
    /// Build item completed
    BuildCompleted { colony: ColonyId, item: BuildItem },
    /// Colony produced resources
    ColonyProduced {
        colony: ColonyId,
        credits: i64,
        research: i64,
    },
    /// Fleet was created
    FleetCreated { fleet: FleetId, location: StarId },
    /// A technology was selected for research
    ResearchSelected { tech: TechId },
    /// Research points were generated empire-wide this turn
    ScienceGenerated { empire: EmpireId, amount: i64 },
    /// Research progress was made toward the active technology
    ResearchProgress {
        tech: TechId,
        gained: i64,
        total: i64,
        cost: i64,
    },
    /// A technology research was completed
    ResearchCompleted { tech: TechId },
    /// A scout fleet has been dispatched toward an unexplored system
    ScoutDispatched {
        fleet: FleetId,
        destination: StarId,
        turns_remaining: u32,
    },
    /// A star system has been explored by a scout
    SystemExplored { star: StarId },
    /// A fleet has departed toward an explored system (multi-turn movement)
    FleetDeparted {
        fleet: FleetId,
        from: StarId,
        to: StarId,
        turns_remaining: u32,
    },
    /// A fleet has arrived at its destination
    FleetArrived { fleet: FleetId, star: StarId },
    /// A colonizer fleet has successfully founded a new colony
    ColonizationCompleted {
        empire: EmpireId,
        fleet: FleetId,
        star: StarId,
        planet_index: usize,
        colony: ColonyId,
    },
    /// Per-empire economy summary for this turn
    EconomySummary {
        empire: EmpireId,
        /// Credits income generated by colonies this turn (before maintenance)
        credits_income: i64,
        /// Credit maintenance cost from fleets and buildings this turn
        maintenance: i64,
        /// Total food produced by colonies this turn
        food_produced: i64,
        /// Total food consumed by population this turn
        food_consumed: i64,
    },
    /// Empire food supply is negative — population is underfed
    FoodShortage {
        empire: EmpireId,
        /// How far below zero the food stockpile fell (positive deficit amount)
        deficit: i64,
    },
    /// Empire credit balance is negative — maintenance exceeds income
    CreditDeficit {
        empire: EmpireId,
        /// How far below zero the credit balance fell (positive deficit amount)
        deficit: i64,
    },
    /// An error occurred
    Error { message: String },
}

impl Event {
    /// Create an error event
    pub fn error(message: impl Into<String>) -> Self {
        Event::Error {
            message: message.into(),
        }
    }

    /// Convert event to a log message
    pub fn to_log_message(&self) -> String {
        match self {
            Event::TurnAdvanced { new_turn } => format!("Turn {} begins", new_turn),
            Event::ColonyFocusSet { colony } => format!("Colony {} focus updated", colony.0),
            Event::FleetMoved { fleet, from, to } => {
                format!("Fleet {} moved from {} to {}", fleet.0, from.0, to.0)
            }
            Event::BuildQueued { colony, item } => {
                format!("Colony {} queued {}", colony.0, item.name())
            }
            Event::BuildCancelled { colony } => {
                format!("Colony {} cancelled build", colony.0)
            }
            Event::BuildCompleted { colony, item } => {
                format!("Colony {} completed {}", colony.0, item.name())
            }
            Event::ColonyProduced {
                colony,
                credits,
                research,
            } => {
                format!(
                    "Colony {} produced {} credits, {} research",
                    colony.0, credits, research
                )
            }
            Event::FleetCreated { fleet, location } => {
                format!("Fleet {} created at star {}", fleet.0, location.0)
            }
            Event::ResearchSelected { tech } => {
                format!("Research started: tech {}", tech.0)
            }
            Event::ScienceGenerated { empire, amount } => {
                format!("Empire {} generated {} science this turn", empire.0, amount)
            }
            Event::ResearchProgress {
                tech,
                gained,
                total,
                cost,
            } => {
                format!(
                    "Research: +{} rp on tech {} ({}/{} rp)",
                    gained, tech.0, total, cost
                )
            }
            Event::ResearchCompleted { tech } => {
                format!("Research complete: tech {}", tech.0)
            }
            Event::ScoutDispatched {
                fleet,
                destination,
                turns_remaining,
            } => {
                format!(
                    "Scout {} dispatched to system {} ({} turns)",
                    fleet.0, destination.0, turns_remaining
                )
            }
            Event::SystemExplored { star } => {
                format!("System {} explored", star.0)
            }
            Event::FleetDeparted {
                fleet,
                from,
                to,
                turns_remaining,
            } => {
                format!(
                    "Fleet {} departed from {} toward {} ({} turns)",
                    fleet.0, from.0, to.0, turns_remaining
                )
            }
            Event::FleetArrived { fleet, star } => {
                format!("Fleet {} arrived at system {}", fleet.0, star.0)
            }
            Event::ColonizationCompleted {
                empire,
                fleet: _,
                star,
                planet_index,
                colony,
            } => {
                format!(
                    "Empire {} founded colony {} at system {} planet {}",
                    empire.0, colony.0, star.0, planet_index
                )
            }
            Event::EconomySummary {
                empire,
                credits_income,
                maintenance,
                food_produced,
                food_consumed,
            } => {
                format!(
                    "Empire {} economy: +{} credits income, -{} maintenance, +{} food, -{} consumed",
                    empire.0, credits_income, maintenance, food_produced, food_consumed
                )
            }
            Event::FoodShortage { empire, deficit } => {
                format!(
                    "WARNING: Empire {} food shortage — deficit {}",
                    empire.0, deficit
                )
            }
            Event::CreditDeficit { empire, deficit } => {
                format!(
                    "WARNING: Empire {} credit deficit — deficit {}",
                    empire.0, deficit
                )
            }
            Event::Error { message } => format!("Error: {}", message),
        }
    }

    /// Check if this is an error event
    pub fn is_error(&self) -> bool {
        matches!(self, Event::Error { .. })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[cfg(feature = "serde")]
    #[test]
    fn event_serialization() {
        let event = Event::TurnAdvanced { new_turn: 5 };
        let json = serde_json::to_string(&event).unwrap();
        let parsed: Event = serde_json::from_str(&json).unwrap();
        assert_eq!(event, parsed);
    }

    #[test]
    fn error_event() {
        let event = Event::error("Something went wrong");
        assert!(event.is_error());
        match event {
            Event::Error { message } => assert_eq!(message, "Something went wrong"),
            _ => panic!("Expected error event"),
        }
    }

    #[test]
    fn log_message_formatting() {
        let event = Event::TurnAdvanced { new_turn: 10 };
        assert_eq!(event.to_log_message(), "Turn 10 begins");

        let event = Event::Error {
            message: "Test error".to_string(),
        };
        assert_eq!(event.to_log_message(), "Error: Test error");

        // Verify numeric IDs are formatted without debug brackets
        let event = Event::ColonyFocusSet {
            colony: crate::state::ColonyId(7),
        };
        assert_eq!(event.to_log_message(), "Colony 7 focus updated");

        let event = Event::FleetMoved {
            fleet: crate::state::FleetId(1),
            from: crate::state::StarId(2),
            to: crate::state::StarId(3),
        };
        assert_eq!(event.to_log_message(), "Fleet 1 moved from 2 to 3");

        let event = Event::ResearchSelected {
            tech: crate::state::TechId(3),
        };
        assert_eq!(event.to_log_message(), "Research started: tech 3");

        let event = Event::ScienceGenerated {
            empire: crate::state::EmpireId(1),
            amount: 42,
        };
        assert_eq!(
            event.to_log_message(),
            "Empire 1 generated 42 science this turn"
        );

        let event = Event::ResearchProgress {
            tech: crate::state::TechId(2),
            gained: 10,
            total: 30,
            cost: 80,
        };
        assert_eq!(
            event.to_log_message(),
            "Research: +10 rp on tech 2 (30/80 rp)"
        );

        let event = Event::ResearchCompleted {
            tech: crate::state::TechId(1),
        };
        assert_eq!(event.to_log_message(), "Research complete: tech 1");

        let event = Event::ScoutDispatched {
            fleet: crate::state::FleetId(2),
            destination: crate::state::StarId(9),
            turns_remaining: 3,
        };
        assert_eq!(
            event.to_log_message(),
            "Scout 2 dispatched to system 9 (3 turns)"
        );

        let event = Event::SystemExplored {
            star: crate::state::StarId(9),
        };
        assert_eq!(event.to_log_message(), "System 9 explored");
    }

    #[test]
    fn scout_dispatched_is_not_error() {
        let event = Event::ScoutDispatched {
            fleet: crate::state::FleetId(1),
            destination: crate::state::StarId(5),
            turns_remaining: 3,
        };
        assert!(!event.is_error());
    }

    #[test]
    fn system_explored_is_not_error() {
        let event = Event::SystemExplored {
            star: crate::state::StarId(5),
        };
        assert!(!event.is_error());
    }

    #[cfg(feature = "serde")]
    #[test]
    fn scout_dispatched_serialization() {
        let event = Event::ScoutDispatched {
            fleet: crate::state::FleetId(1),
            destination: crate::state::StarId(5),
            turns_remaining: 3,
        };
        let json = serde_json::to_string(&event).unwrap();
        let parsed: Event = serde_json::from_str(&json).unwrap();
        assert_eq!(event, parsed);
    }

    #[cfg(feature = "serde")]
    #[test]
    fn system_explored_serialization() {
        let event = Event::SystemExplored {
            star: crate::state::StarId(7),
        };
        let json = serde_json::to_string(&event).unwrap();
        let parsed: Event = serde_json::from_str(&json).unwrap();
        assert_eq!(event, parsed);
    }

    #[test]
    fn fleet_departed_log_message() {
        let event = Event::FleetDeparted {
            fleet: crate::state::FleetId(2),
            from: crate::state::StarId(3),
            to: crate::state::StarId(7),
            turns_remaining: 2,
        };
        assert_eq!(
            event.to_log_message(),
            "Fleet 2 departed from 3 toward 7 (2 turns)"
        );
        assert!(!event.is_error());
    }

    #[test]
    fn fleet_arrived_log_message() {
        let event = Event::FleetArrived {
            fleet: crate::state::FleetId(4),
            star: crate::state::StarId(9),
        };
        assert_eq!(event.to_log_message(), "Fleet 4 arrived at system 9");
        assert!(!event.is_error());
    }

    #[cfg(feature = "serde")]
    #[test]
    fn fleet_departed_serialization() {
        let event = Event::FleetDeparted {
            fleet: crate::state::FleetId(1),
            from: crate::state::StarId(2),
            to: crate::state::StarId(5),
            turns_remaining: 2,
        };
        let json = serde_json::to_string(&event).unwrap();
        let parsed: Event = serde_json::from_str(&json).unwrap();
        assert_eq!(event, parsed);
    }

    #[cfg(feature = "serde")]
    #[test]
    fn fleet_arrived_serialization() {
        let event = Event::FleetArrived {
            fleet: crate::state::FleetId(3),
            star: crate::state::StarId(8),
        };
        let json = serde_json::to_string(&event).unwrap();
        let parsed: Event = serde_json::from_str(&json).unwrap();
        assert_eq!(event, parsed);
    }

    #[test]
    fn economy_summary_log_message() {
        let event = Event::EconomySummary {
            empire: crate::state::EmpireId(1),
            credits_income: 10,
            maintenance: 2,
            food_produced: 8,
            food_consumed: 5,
        };
        assert_eq!(
            event.to_log_message(),
            "Empire 1 economy: +10 credits income, -2 maintenance, +8 food, -5 consumed"
        );
        assert!(!event.is_error());
    }

    #[test]
    fn food_shortage_log_message() {
        let event = Event::FoodShortage {
            empire: crate::state::EmpireId(1),
            deficit: 3,
        };
        assert_eq!(
            event.to_log_message(),
            "WARNING: Empire 1 food shortage — deficit 3"
        );
        assert!(!event.is_error());
    }

    #[test]
    fn credit_deficit_log_message() {
        let event = Event::CreditDeficit {
            empire: crate::state::EmpireId(1),
            deficit: 5,
        };
        assert_eq!(
            event.to_log_message(),
            "WARNING: Empire 1 credit deficit — deficit 5"
        );
        assert!(!event.is_error());
    }

    #[cfg(feature = "serde")]
    #[test]
    fn economy_summary_serialization() {
        let event = Event::EconomySummary {
            empire: crate::state::EmpireId(1),
            credits_income: 10,
            maintenance: 2,
            food_produced: 8,
            food_consumed: 5,
        };
        let json = serde_json::to_string(&event).unwrap();
        let parsed: Event = serde_json::from_str(&json).unwrap();
        assert_eq!(event, parsed);
    }

    #[cfg(feature = "serde")]
    #[test]
    fn food_shortage_serialization() {
        let event = Event::FoodShortage {
            empire: crate::state::EmpireId(2),
            deficit: 7,
        };
        let json = serde_json::to_string(&event).unwrap();
        let parsed: Event = serde_json::from_str(&json).unwrap();
        assert_eq!(event, parsed);
    }

    #[cfg(feature = "serde")]
    #[test]
    fn credit_deficit_serialization() {
        let event = Event::CreditDeficit {
            empire: crate::state::EmpireId(2),
            deficit: 4,
        };
        let json = serde_json::to_string(&event).unwrap();
        let parsed: Event = serde_json::from_str(&json).unwrap();
        assert_eq!(event, parsed);
    }
}
