//! Events emitted by the game engine

use crate::state::{BuildItem, ColonyId, EmpireId, FleetId, StarId, TechId};
#[cfg(feature = "serde")]
use serde::{Deserialize, Serialize};

/// Events generated by the game engine in response to commands
#[derive(Debug, Clone, PartialEq, Eq)]
#[cfg_attr(feature = "serde", derive(Serialize, Deserialize))]
pub enum Event {
    /// Turn has advanced
    TurnAdvanced { new_turn: u32 },
    /// Colony focus was set
    ColonyFocusSet { colony: ColonyId },
    /// Fleet has moved
    FleetMoved {
        fleet: FleetId,
        from: StarId,
        to: StarId,
    },
    /// Build item was queued
    BuildQueued { colony: ColonyId, item: BuildItem },
    /// Build item was cancelled
    BuildCancelled { colony: ColonyId },
    /// Build item completed
    BuildCompleted { colony: ColonyId, item: BuildItem },
    /// Colony produced resources
    ColonyProduced {
        colony: ColonyId,
        credits: i64,
        research: i64,
    },
    /// Fleet was created
    FleetCreated { fleet: FleetId, location: StarId },
    /// A technology was selected for research
    ResearchSelected { tech: TechId },
    /// Research points were generated empire-wide this turn
    ScienceGenerated { empire: EmpireId, amount: i64 },
    /// Research progress was made toward the active technology
    ResearchProgress {
        tech: TechId,
        gained: i64,
        total: i64,
        cost: i64,
    },
    /// A technology research was completed
    ResearchCompleted { tech: TechId },
    /// An error occurred
    Error { message: String },
}

impl Event {
    /// Create an error event
    pub fn error(message: impl Into<String>) -> Self {
        Event::Error {
            message: message.into(),
        }
    }

    /// Convert event to a log message
    pub fn to_log_message(&self) -> String {
        match self {
            Event::TurnAdvanced { new_turn } => format!("Turn {} begins", new_turn),
            Event::ColonyFocusSet { colony } => format!("Colony {} focus updated", colony.0),
            Event::FleetMoved { fleet, from, to } => {
                format!("Fleet {} moved from {} to {}", fleet.0, from.0, to.0)
            }
            Event::BuildQueued { colony, item } => {
                format!("Colony {} queued {}", colony.0, item.name())
            }
            Event::BuildCancelled { colony } => {
                format!("Colony {} cancelled build", colony.0)
            }
            Event::BuildCompleted { colony, item } => {
                format!("Colony {} completed {}", colony.0, item.name())
            }
            Event::ColonyProduced {
                colony,
                credits,
                research,
            } => {
                format!(
                    "Colony {} produced {} credits, {} research",
                    colony.0, credits, research
                )
            }
            Event::FleetCreated { fleet, location } => {
                format!("Fleet {} created at star {}", fleet.0, location.0)
            }
            Event::ResearchSelected { tech } => {
                format!("Research started: tech {}", tech.0)
            }
            Event::ScienceGenerated { empire, amount } => {
                format!("Empire {} generated {} science this turn", empire.0, amount)
            }
            Event::ResearchProgress {
                tech,
                gained,
                total,
                cost,
            } => {
                format!(
                    "Research: +{} rp on tech {} ({}/{} rp)",
                    gained, tech.0, total, cost
                )
            }
            Event::ResearchCompleted { tech } => {
                format!("Research complete: tech {}", tech.0)
            }
            Event::Error { message } => format!("Error: {}", message),
        }
    }

    /// Check if this is an error event
    pub fn is_error(&self) -> bool {
        matches!(self, Event::Error { .. })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[cfg(feature = "serde")]
    #[test]
    fn event_serialization() {
        let event = Event::TurnAdvanced { new_turn: 5 };
        let json = serde_json::to_string(&event).unwrap();
        let parsed: Event = serde_json::from_str(&json).unwrap();
        assert_eq!(event, parsed);
    }

    #[test]
    fn error_event() {
        let event = Event::error("Something went wrong");
        assert!(event.is_error());
        match event {
            Event::Error { message } => assert_eq!(message, "Something went wrong"),
            _ => panic!("Expected error event"),
        }
    }

    #[test]
    fn log_message_formatting() {
        let event = Event::TurnAdvanced { new_turn: 10 };
        assert_eq!(event.to_log_message(), "Turn 10 begins");

        let event = Event::Error {
            message: "Test error".to_string(),
        };
        assert_eq!(event.to_log_message(), "Error: Test error");

        // Verify numeric IDs are formatted without debug brackets
        let event = Event::ColonyFocusSet {
            colony: crate::state::ColonyId(7),
        };
        assert_eq!(event.to_log_message(), "Colony 7 focus updated");

        let event = Event::FleetMoved {
            fleet: crate::state::FleetId(1),
            from: crate::state::StarId(2),
            to: crate::state::StarId(3),
        };
        assert_eq!(event.to_log_message(), "Fleet 1 moved from 2 to 3");

        let event = Event::ResearchSelected {
            tech: crate::state::TechId(3),
        };
        assert_eq!(event.to_log_message(), "Research started: tech 3");

        let event = Event::ScienceGenerated {
            empire: crate::state::EmpireId(1),
            amount: 42,
        };
        assert_eq!(
            event.to_log_message(),
            "Empire 1 generated 42 science this turn"
        );

        let event = Event::ResearchProgress {
            tech: crate::state::TechId(2),
            gained: 10,
            total: 30,
            cost: 80,
        };
        assert_eq!(
            event.to_log_message(),
            "Research: +10 rp on tech 2 (30/80 rp)"
        );

        let event = Event::ResearchCompleted {
            tech: crate::state::TechId(1),
        };
        assert_eq!(event.to_log_message(), "Research complete: tech 1");
    }
}
